# Generated by Django 6.0.3 on 2026-03-25 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_corta', models.CharField(help_text='Un resumen rápido para la tarjeta.', max_length=300)),
                ('documentacion', models.TextField(help_text='Detalles técnicos completos.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('enlace_repositorio', models.URLField(blank=True, help_text='GitHub/GitLab', null=True)),
            ],
        ),
    ]
