# Generated by Django 6.0.3 on 2026-03-25 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_categoria_post_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='post',
            name='enlace_Evento',
            field=models.URLField(blank=True, help_text='Más información', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
