# Generated by Django 6.0.3 on 2026-06-11 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.CharField(help_text='Resumen mostrado en la tarjeta.', max_length=300),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='documentacion',
            field=models.TextField(help_text='Descripción técnica completa.'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='enlace_repositorio',
            field=models.URLField(blank=True, help_text='GitHub / GitLab / Página del proyecto', null=True),
        ),
        migrations.CreateModel(
            name='ProyectoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/carrusel/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.proyecto')),
            ],
        ),
    ]
